# Generated by Django 5.1.2 on 2024-11-09 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('maximoGoleadorEquipo', models.CharField(max_length=50)),
                ('maximoAsistenteEquipo', models.CharField(max_length=50)),
                ('AnioCreacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('anio', models.DateField()),
                ('maximoGoleadorLiga', models.CharField(max_length=25)),
                ('maximoAsistenteLiga', models.CharField(max_length=50)),
                ('presidenteLiga', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('goles', models.CharField(max_length=50)),
                ('posicion', models.CharField(max_length=50)),
                ('anioDeUnion', models.DateField()),
                ('fechaNacimiento', models.DateField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='ligaAPP.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='ligaAPP.liga'),
        ),
    ]
