# Generated by Django 5.1.3 on 2024-11-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligaAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='imagenEquipo',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='imagenJugador',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='liga',
            name='imagenLiga',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
